In [4]:
import numpy as np 

## Datatypes and Attributes 

In [5]:
a1 = np.array([1,2,3])

In [6]:
a1


array([1, 2, 3])

In [7]:
type(a1)

numpy.ndarray

In [8]:
a1.size

3

In [9]:
a1.dtype

dtype('int64')

In [10]:
ones = np.ones((2,3))

In [11]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [12]:
ones.dtype

dtype('float64')

In [13]:
range_array = np.arange(0,10,2)

In [14]:
random_array = np.random.randint(0,10,(2,3))

In [15]:
random_array

array([[0, 6, 6],
       [8, 7, 7]])

In [16]:
random_array

array([[0, 6, 6],
       [8, 7, 7]])

In [17]:
np.random.seed(7)
randomarr = np.random.random((5,3))
randomarr

array([[0.07630829, 0.77991879, 0.43840923],
       [0.72346518, 0.97798951, 0.53849587],
       [0.50112046, 0.07205113, 0.26843898],
       [0.4998825 , 0.67923   , 0.80373904],
       [0.38094113, 0.06593635, 0.2881456 ]])

In [18]:
a2 = random_array

In [19]:
ones * a2 

array([[0., 6., 6.],
       [8., 7., 7.]])

In [20]:
listy_list = [1,2,3]

In [21]:
type(listy_list)

list

In [22]:
sum(listy_list)

6

In [23]:
sum(a1)

6

In [24]:
np.sum(a1)

6

In [25]:
np.std(a1)

0.816496580927726

In [26]:
a2 = np.array([list(range(3)), list(range(3))])

In [27]:
a2

array([[0, 1, 2],
       [0, 1, 2]])

In [28]:
a2.T

array([[0, 0],
       [1, 1],
       [2, 2]])

In [29]:
np.random.seed(0)
mat1 = np.random.randint(1,65,(5,3))
mat2 = np.random.randint(1,10,(5,3))

In [30]:
np.dot(mat1,mat2.T)

array([[ 945, 1131,  825,  861,  561],
       [ 165,  519,  377,  269,  377],
       [ 416,  428,  176,  276,  224],
       [ 480,  724,  530,  494,  414],
       [ 563,  507,  423,  481,  175]])

In [38]:
np.random.seed(0)
sales_amounts = np.random.randint(0,20,(5,3))
sales_amounts

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [40]:
# Dataframe creation

weekly_sales = pd.DataFrame(sales_amounts,
                           index = ["Mon","Tues","Wed","Thurs","Fri"],
                           columns = ["P1","P2","P3"])

In [41]:
weekly_sales

P1  P2  P3
Mon    12  15   0
Tues    3   3   7
Wed     9  19  18
Thurs   4   6  12
Fri     1   6   7

In [50]:
prices = np.array([23,3,10])
prices.reshape(1,3).shape

(1, 3)

In [52]:
prices.shape

(3,)

In [53]:
pricesFrame = pd.DataFrame(prices.reshape(1,3), index = ["Price"],columns = ["P1","P2","P3"])

In [54]:
prices

array([23,  3, 10])

In [56]:
total_sales = weekly_sales.dot(prices.reshape(3,1))

In [57]:
weekly_sales["Total "] = total_sales

In [58]:
weekly_sales

P1  P2  P3  Total 
Mon    12  15   0     321
Tues    3   3   7     148
Wed     9  19  18     444
Thurs   4   6  12     230
Fri     1   6   7     111

In [59]:
# sorting test
random_array

array([[0, 6, 6],
       [8, 7, 7]])

In [60]:
random_array.sort()

In [61]:
random_array


array([[0, 6, 6],
       [7, 7, 8]])

In [62]:
np.sort(random_array)

array([[0, 6, 6],
       [7, 7, 8]])

In [63]:
np.argsort(random_array)

array([[0, 1, 2],
       [0, 1, 2]])

## Some fotos

<img src = "numpy-images/panda.png">

In [73]:
# turn image into np array 
from matplotlib.image import imread

In [75]:
panda = imread("numpy-images/panda.png")

In [76]:
panda.size,panda.shape, panda.ndim

(24465000, (2330, 3500, 3), 3)